Update cmake-multi-platform.yml

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -28,10 +28,11 @@ jobs:
           mingw-w64-x86_64-openmp
     - name: Configure CMake
       run: cmake -B build -DCMAKE_BUILD_TYPE=Release
-    - name: Build and Resolve function call ambiguity
+    - name: Build
+      run: cmake --build build --config Release
+    - name: Resolve function call ambiguity
       shell: cmd
       run: |
-        cmake --build build --config Release
         set source_file=build\_deps\directxtk-src\Audio\WAVFileReader.cpp
         set temp_file=%temp%\WAVFileReader_temp.cpp
         type nul > %temp_file%
@@ -43,6 +44,12 @@ jobs:
           endlocal
         )
         move /y %temp_file% %source_file%
+    - name: Check DLL Existence
+      run: |
+        if not exist build\SnowClient.dll (
+          echo "SnowClient.dll not found in the build directory. Build may have failed."
+          exit 1
+        )
     - name: Upload DLL
       uses: actions/upload-artifact@v3
       with:
