Update cmake-multi-platform.yml

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -26,10 +26,16 @@ jobs:
           mingw-w64-x86_64-binutils
           mingw-w64-x86_64-toolchain
           mingw-w64-x86_64-openmp
+    - name: Check find command availability
+      shell: bash
+      run: |
+        if! command -v find &>/dev/null; then
+          echo "find command not found. Please check the environment."
+          exit 1
+        fi
     - name: Locate WAVFileReader.cpp
       shell: bash
       run: |
-        # 查找 WAVFileReader.cpp 文件的位置并设置为环境变量
         source_file=$(find. -name "WAVFileReader.cpp" | grep -i "directxtk-src/Audio")
         echo "SOURCE_FILE=$source_file" >> $GITHUB_ENV
     - name: Resolve function call ambiguity
